services:
  mysql:
    image: mysql:8.1
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword       # пароль для root
      MYSQL_DATABASE: mydb                     # назва бази даних
      MYSQL_USER: myuser                       # користувач
      MYSQL_PASSWORD: userpassword             # пароль користувача
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql             # щоб база зберігалась після перезапуску
    command: --default-time-zone='+00:00'     # або UTC, щоб уникнути проблем з таймзоною

volumes:
  mysql_data: